[tool.ruff]
target-version="py39"
lint.select = [
    "ALL"
]
ignore = [ 
    "D100", #モジュールのDOCがない場合
    "D103", #関数のDOCがない場合
    "S104", #0.0.0.0の指定禁止
    "ANN201",
]


line-length = 119

[tool.ruff.lint.isort]
force-single-line = true